product-name = "tauri-leptos-example"
version = "0.5.5"
identifier = "com.tauri-leptos-example.dev"

[build]
dev-url = "http://127.0.0.1:8080"
before-dev-command = { cwd = "../src-ui", script = "trunk serve" }
before-build-command = { cwd = "../src-ui", script = "trunk build" }
frontend-dist = "../src-ui/dist"

[bundle]
active = true
icon = ["icons/icon.ico"]

[app]
with-global-tauri = true

[[app.windows]]
title = "Tauri Leptos Example"
width = 800
height = 600
