[package]
name = "src-ui"
version = "0.2.0"
edition.workspace = true

[lib]
name = "src_ui_lib"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-beta2", features = ["csr"] }
thaw = { version = "0.4.0-beta", features = ["csr"] }

[dev-dependencies]
wasm-bindgen = "0.2.93"
wasm-bindgen-test = "0.3.43"

[dev-dependencies.web-sys]
features = ["HtmlElement", "XPathResult"]
version = "0.3.70"
