[package]
name = "src-ui"
version = "0.4.0"
edition.workspace = true

[lib]
name = "src_ui_lib"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
futures = "0.3.30"
leptos = { version = "0.7.0-gamma", features = ["csr"] }
log = "0.4.22"
serde = { version = "1", features = ["derive"] }
# thaw = { version = "0.4.0-beta3" }

[dependencies.thaw]
git = "https://github.com/thaw-ui/thaw"
branch = "main"

[dependencies.tauri-sys]
git = "https://github.com/JonasKruckenberg/tauri-sys"
branch = "v2"
features = ["all"]

[dev-dependencies]
wasm-bindgen = "0.2.93"
wasm-bindgen-test = "0.3.43"

[dev-dependencies.web-sys]
features = ["HtmlElement", "XPathResult"]
version = "0.3.70"
