[package]
name = "src-ui"
version = "0.1.2"
edition.workspace = true

[lib]
name = "src_ui_lib"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-gamma", features = ["csr"] }
