[package]
name = "src-ui"
version = "0.2.3"
edition.workspace = true

[lib]
name = "src_ui_lib"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-gamma2", features = ["csr"] }
# thaw = { version = "0.4.0-beta3"}

[dependencies.thaw]
git = "https://github.com/thaw-ui/thaw"
branch = "main"

[dev-dependencies]
wasm-bindgen = "0.2.93"
wasm-bindgen-test = "0.3.43"

[dev-dependencies.web-sys]
version = "0.3.70"
features = ["HtmlElement", "XPathResult"]
