[package]
name = "src-ui"
version = "0.2.8"
edition.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-rc1", features = ["csr"] }
# thaw = { version = "0.4.0-beta3"}

[dependencies.thaw]
git = "https://github.com/thaw-ui/thaw"
branch = "main"

[dev-dependencies]
wasm-bindgen = "0.2.95"
wasm-bindgen-test = "0.3.45"

[dev-dependencies.web-sys]
version = "0.3.72"
features = ["HtmlElement", "XPathResult"]
